### ISSUE TITLE
eval_scene not running

### ISSUE THREAD

**Issue by lusxvr** [opennerf/opennerf#5]
The paths in eval_scene in train_eval_replica_semantics.py are still fixed, while in train_scene they make use of the modifiable CONDA_DIR and PREFIX variables.

Just an issue and not a PR since Its a super minor thing and I didnt know if you wanted contributions

**Comment by lusxvr** [comment]
In` eval_semantics`, `pr_files` is read in, e.g. `opennerf/outputs/replica_office0/opennerf/run_debug/semantics_office0.txt` unfortunately this file does not exist in my project after `eval_scene` is run through `train_eval_replica_semantics.py`. 
This is how my `outputs` folder looks:

![image](https://github.com/opennerf/opennerf/assets/87134473/119f8d9c-9873-493e-93ad-0da2c17721c4)

**Comment by francisengelmann** [comment]
Do you have the full output, to see if one of the earlier steps printed an error?

**Comment by lusxvr** [comment]
Yes, of course

```
(adl4cv) luca_luis@SWS01:~/adl4cv/opennerf$ python scripts/train_eval_replica_semantics.py
2024-05-29 09:33:04.903082: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-29 09:33:04.903296: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-29 09:33:04.905279: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-29 09:33:04.927804: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-29 09:33:05.295453: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/luca_luis/anaconda3/envs/adl4cv/lib/python3.10/site-packages/tinycudann/modules.py:52: UserWarning: tinycudann was built for lower compute capability (75) than the system's (86). Performance may be suboptimal.
  warnings.warn(f"tinycudann was built for lower compute capability ({cc}) than the system's ({system_compute_capability}). Performance may be suboptimal.")
[09:33:08] Using --data alias for --data.pipeline.datamanager.data                                          train.py:230
──────────────────────────────────────────────────────── Config ────────────────────────────────────────────────────────
TrainerConfig(
    _target=<class 'nerfstudio.engine.trainer.Trainer'>,
    output_dir=PosixPath('/home/luca_luis/adl4cv/opennerf/outputs'),
    method_name='opennerf',
    experiment_name='replica_office0',
    project_name='nerfstudio-project',
    timestamp='test_eval',
    machine=MachineConfig(seed=42, num_devices=1, num_machines=1, machine_rank=0, dist_url='auto', device_type='cuda'),
    logging=LoggingConfig(
        relative_log_dir=PosixPath('.'),
        steps_per_log=10,
        max_buffer_size=20,
        local_writer=LocalWriterConfig(
            _target=<class 'nerfstudio.utils.writer.LocalWriter'>,
            enable=True,
            stats_to_track=(
                <EventName.ITER_TRAIN_TIME: 'Train Iter (time)'>,
                <EventName.TRAIN_RAYS_PER_SEC: 'Train Rays / Sec'>,
                <EventName.CURR_TEST_PSNR: 'Test PSNR'>,
                <EventName.VIS_RAYS_PER_SEC: 'Vis Rays / Sec'>,
                <EventName.TEST_RAYS_PER_SEC: 'Test Rays / Sec'>,
                <EventName.ETA: 'ETA (time)'>
            ),
            max_log_size=10
        ),
        profiler='basic'
    ),
    viewer=ViewerConfig(
        relative_log_filename='viewer_log_filename.txt',
        websocket_port=None,
        websocket_port_default=7007,
        websocket_host='0.0.0.0',
        num_rays_per_chunk=2048,
        max_num_display_images=512,
        quit_on_train_completion=False,
        image_format='jpeg',
        jpeg_quality=75,
        make_share_url=False,
        camera_frustum_scale=0.1,
        default_composite_depth=True
    ),
    pipeline=OpenNerfPipelineConfig(
        _target=<class 'opennerf.opennerf_pipeline.OpenNerfPipeline'>,
        datamanager=OpenNerfDataManagerConfig(
            _target=<class 'opennerf.opennerf_datamanager.OpenNerfDataManager'>,
            data=PosixPath('/home/luca_luis/adl4cv/replica_opennerf/office0'),
            masks_on_gpu=False,
            images_on_gpu=False,
            dataparser=NerfstudioDataParserConfig(
                _target=<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.Nerfstudio'>,
                data=PosixPath('.'),
                scale_factor=1.0,
                downscale_factor=None,
                scene_scale=1.0,
                orientation_method='up',
                center_method='poses',
                auto_scale_poses=True,
                eval_mode='fraction',
                train_split_fraction=0.99,
                eval_interval=8,
                depth_unit_scale_factor=0.001,
                mask_color=None,
                load_3D_points=False
            ),
            train_num_rays_per_batch=2048,
            train_num_images_to_sample_from=-1,
            train_num_times_to_repeat_images=-1,
            eval_num_rays_per_batch=4096,
            eval_num_images_to_sample_from=-1,
            eval_num_times_to_repeat_images=-1,
            eval_image_indices=(0,),
            collate_fn=<function nerfstudio_collate at 0x7f3cebe143a0>,
            camera_res_scale_factor=1.0,
            patch_size=1,
            camera_optimizer=None,
            pixel_sampler=PixelSamplerConfig(
                _target=<class 'nerfstudio.data.pixel_samplers.PixelSampler'>,
                num_rays_per_batch=4096,
                keep_full_image=False,
                is_equirectangular=False,
                ignore_mask=False,
                fisheye_crop_radius=None,
                rejection_sample_mask=True,
                max_num_iterations=100
            ),
            patch_tile_size_range=(0.05, 0.5),
            patch_tile_size_res=7,
            patch_stride_scaler=0.5
        ),
        model=OpenNerfModelConfig(
            _target=<class 'opennerf.opennerf_model.OpenNerfModel'>,
            enable_collider=True,
            collider_params={'near_plane': 2.0, 'far_plane': 6.0},
            loss_coefficients={'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0},
            eval_num_rays_per_chunk=32768,
            prompt=None,
            near_plane=0.05,
            far_plane=1000.0,
            background_color='last_sample',
            hidden_dim=64,
            hidden_dim_color=64,
            hidden_dim_transient=64,
            num_levels=16,
            base_res=16,
            max_res=2048,
            log2_hashmap_size=19,
            features_per_level=2,
            num_proposal_samples_per_ray=(256, 96),
            num_nerf_samples_per_ray=48,
            proposal_update_every=5,
            proposal_warmup=5000,
            num_proposal_iterations=2,
            use_same_proposal_network=False,
            proposal_net_args_list=[
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 128, 'use_linear': False},
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 256, 'use_linear': False}
            ],
            proposal_initial_sampler='piecewise',
            interlevel_loss_mult=1.0,
            distortion_loss_mult=0.002,
            orientation_loss_mult=0.0001,
            pred_normal_loss_mult=0.001,
            use_proposal_weight_anneal=True,
            use_appearance_embedding=True,
            use_average_appearance_embedding=True,
            proposal_weights_anneal_slope=10.0,
            proposal_weights_anneal_max_num_iters=1000,
            use_single_jitter=True,
            predict_normals=False,
            disable_scene_contraction=False,
            use_gradient_scaling=False,
            implementation='tcnn',
            appearance_embed_dim=32,
            average_init_density=1.0,
            camera_optimizer=CameraOptimizerConfig(
                _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
                mode='SO3xR3',
                trans_l2_penalty=0.01,
                rot_l2_penalty=0.001,
                optimizer=None,
                scheduler=None
            ),
            clip_loss_weight=0.1,
            dino_loss_weight=0.0,
            openseg_loss_weight=1.0,
            openseg_loss='MSE',
            n_scales=30,
            max_scale=1.5,
            num_opennerf_samples=24,
            hashgrid_layers=(12, 12),
            hashgrid_resolutions=((16, 128), (128, 512)),
            hashgrid_sizes=(19, 19),
            num_hidden_clip_layers=1
        ),
        network=BaseImageEncoderConfig(_target=<class 'opennerf.encoders.image_encoder.BaseImageEncoder'>)
    ),
    optimizers={
        'proposal_networks': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'fields': {
            'optimizer': RAdamOptimizerConfig(
                _target=<class 'torch.optim.radam.RAdam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=0.001,
                warmup_steps=0,
                max_steps=30000,
                ramp='cosine'
            )
        },
        'opennerf': {
            'optimizer': RAdamOptimizerConfig(
                _target=<class 'torch.optim.radam.RAdam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=1e-09
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=0.001,
                warmup_steps=0,
                max_steps=4000,
                ramp='cosine'
            )
        }
    },
    vis='wandb',
    data=PosixPath('/home/luca_luis/adl4cv/replica_opennerf/office0'),
    prompt=None,
    relative_model_dir=PosixPath('nerfstudio_models'),
    load_scheduler=True,
    steps_per_save=2000,
    steps_per_eval_batch=500000,
    steps_per_eval_image=500000,
    steps_per_eval_all_images=500000,
    max_num_iterations=30000,
    mixed_precision=True,
    use_grad_scaler=False,
    save_only_latest_checkpoint=True,
    load_dir=None,
    load_step=None,
    load_config=None,
    load_checkpoint=None,
    log_gradients=False,
    gradient_accumulation_steps={}
)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
           Saving config to:                                                                    experiment_config.py:136
           /home/luca_luis/adl4cv/opennerf/outputs/replica_office0/opennerf/test_eval/config.ym                         
           l                                                                                                            
           Saving checkpoints to:                                                                         trainer.py:137
           /home/luca_luis/adl4cv/opennerf/outputs/replica_office0/opennerf/test_eval/nerfstudio_models                 
           Auto image downscale factor of 1                                                 nerfstudio_dataparser.py:484
Setting up training dataset...
Caching all 198 images.
Setting up evaluation dataset...
Caching all 2 images.

The 'camera_opt' param group should be assigned an optimizer in the config. Assigning default optimizers for now. This 
will be removed in a future release.

No Nerfstudio checkpoint to load, so training from scratch.
wandb: Currently logged in as: luis-wiedmann (lusxvr). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.17.0
wandb: Run data is saved locally in /home/luca_luis/adl4cv/opennerf/outputs/replica_office0/opennerf/test_eval/wandb/run-20240529_093315-bhzo3nis
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run replica_office0
wandb: ⭐️ View project at https://wandb.ai/lusxvr/nerfstudio-project
wandb: 🚀 View run at https://wandb.ai/lusxvr/nerfstudio-project/runs/bhzo3nis
logging events to: /home/luca_luis/adl4cv/opennerf/outputs/replica_office0/opennerf/test_eval
[09:33:20] Printing max of 10 lines. Set flag --logging.local-writer.max-log-size=0 to disable line        writer.py:448
           wrapping.                                                                                                    
Step (% Done)       Train Iter (time)    ETA (time)           Train Rays / Sec      
----------------------------------------------------------------------------------- 
29910 (99.70%)      32.475 ms            2 s, 922.777 ms      63.15 K               
29920 (99.73%)      32.426 ms            2 s, 594.075 ms      63.23 K               
29930 (99.77%)      32.702 ms            2 s, 289.113 ms      62.74 K               
29940 (99.80%)      32.608 ms            1 s, 956.491 ms      62.90 K               
29950 (99.83%)      32.405 ms            1 s, 620.234 ms      63.28 K               
29960 (99.87%)      32.612 ms            1 s, 304.473 ms      62.91 K               
29970 (99.90%)      32.647 ms            979.405 ms           62.82 K               
29980 (99.93%)      32.635 ms            652.697 ms           62.84 K               m, 58 s           63.44 K               
29990 (99.97%)      32.650 ms            326.496 ms           62.83 K               
29999 (100.00%)                                                                     
╭────────────────────────────────────────────── 🎉 Training Finished 🎉 ───────────────────────────────────────────────╮
│                        ╷                                                                                             │
│   Config File          │ /home/luca_luis/adl4cv/opennerf/outputs/replica_office0/opennerf/test_eval/config.yml       │
│   Checkpoint Directory │ /home/luca_luis/adl4cv/opennerf/outputs/replica_office0/opennerf/test_eval/nerfstudio_mo…   │
│                        ╵                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.0323              
VanillaPipeline.get_train_loss_dict: 0.0091              
Trainer.eval_iteration: 0.0000              
wandb: | 0.033 MB of 0.033 MB uploaded
wandb: Run history:
wandb:                                     ETA (time) ███▇▇▇▇▇▆▆▆▆▆▅▅▅▅▅▅▄▄▄▄▄▄▃▃▃▃▃▃▂▂▂▂▂▂▁▁▁
wandb:                                GPU Memory (MB) ▁▂▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:                              Train Iter (time) ██▇▅▄▄▃▃▃▃▃▅▃▁▂▃▃▃▂▃▃▂▅▂▂▂▃▃▃▃▃▃▆▃▃▄▂▃▂▃
wandb:                                     Train Loss ▆▄▂▃▅▃▅▅▄▅▄▆▁▅▂▂▅▃▅▆▆▄▄▃▅▁▃▅▅▇▁▄▁▂▅▄█▂▂▃
wandb:         Train Loss Dict/camera_opt_regularizer ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                      Train Loss Dict/dino_loss ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                Train Loss Dict/distortion_loss █▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                Train Loss Dict/interlevel_loss ▆▁▁▂▅▃▄▅▅▅▄▄▄▄▆▅▅▅▅▇▆▆▅▆▇▆█▆▇▄▆▅▆▆▅▅▄▆▇▆
wandb:                   Train Loss Dict/openseg_loss ▆▄▂▃▅▃▅▅▄▅▄▆▁▅▂▂▅▃▅▆▆▄▄▃▅▁▃▅▅▇▁▄▁▂▅▄█▂▂▃
wandb:                       Train Loss Dict/rgb_loss █▃▃▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:     Train Metrics Dict/camera_opt_rotation_max ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:    Train Metrics Dict/camera_opt_rotation_mean ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:  Train Metrics Dict/camera_opt_translation_max ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: Train Metrics Dict/camera_opt_translation_mean ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                  Train Metrics Dict/distortion █▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                        Train Metrics Dict/psnr ▁▃▃▅▅▆▅▅▅▅▆▆▇▇▇▆▆▆▆▇▇▆▇▇▇▇▆▇▇▆▇████▇██▇▇
wandb:                               Train Rays / Sec ▁▁▂▄▅▅▆▆▆▆▆▃▆█▆▅▆▆▇▆▅▆▄▇▆▆▆▆▆▆▆▆▁▆▆▅▇▆▆▆
wandb:                             Train Total (time) ▁
wandb:                       learning_rate/camera_opt ██▇▇▆▆▆▅▅▅▅▄▄▄▄▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁
wandb:                           learning_rate/fields ██▇▇▆▆▆▅▅▅▅▄▄▄▄▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁
wandb:                         learning_rate/opennerf █▆▄▃▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:                                     ETA (time) 0.03249
wandb:                                GPU Memory (MB) 19247.54102
wandb:                              Train Iter (time) 0.03249
wandb:                                     Train Loss 9.31034
wandb:         Train Loss Dict/camera_opt_regularizer 0.0
wandb:                      Train Loss Dict/dino_loss 0.0
wandb:                Train Loss Dict/distortion_loss 0.0
wandb:                Train Loss Dict/interlevel_loss 0.00036
wandb:                   Train Loss Dict/openseg_loss 9.30992
wandb:                       Train Loss Dict/rgb_loss 5e-05
wandb:     Train Metrics Dict/camera_opt_rotation_max 0.0
wandb:    Train Metrics Dict/camera_opt_rotation_mean 0.0
wandb:  Train Metrics Dict/camera_opt_translation_max 0.0
wandb: Train Metrics Dict/camera_opt_translation_mean 0.0
wandb:                  Train Metrics Dict/distortion 0.00068
wandb:                        Train Metrics Dict/psnr 42.84248
wandb:                               Train Rays / Sec 63120.67926
wandb:                             Train Total (time) 2024.34821
wandb:                       learning_rate/camera_opt 0.0001
wandb:                           learning_rate/fields 0.001
wandb:                         learning_rate/opennerf 0.001
wandb: 
wandb: 🚀 View run replica_office0 at: https://wandb.ai/lusxvr/nerfstudio-project/runs/bhzo3nis
wandb: ⭐️ View project at: https://wandb.ai/lusxvr/nerfstudio-project
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./outputs/replica_office0/opennerf/test_eval/wandb/run-20240529_093315-bhzo3nis/logs
/home/luca_luis/anaconda3/envs/adl4cv/bin/python: can't open file '/home/luca_luis/adl4cv/opennerf/opennerf/datasets/replica_semantics.py': [Errno 2] No such file or directory
evaluating 1 scans...
Traceback (most recent call last):
  File "/home/luca_luis/adl4cv/opennerf/scripts/train_eval_replica_semantics.py", line 126, in <module>
    main()
  File "/home/luca_luis/adl4cv/opennerf/scripts/train_eval_replica_semantics.py", line 123, in main
    eval_semantics(experiment_name)
  File "/home/luca_luis/adl4cv/opennerf/scripts/train_eval_replica_semantics.py", line 63, in eval_semantics
    evaluate_scan(pr_files[i], gt_files[i], confusion)
  File "/home/luca_luis/adl4cv/opennerf/scripts/train_eval_replica_semantics.py", line 93, in evaluate_scan
    pr_ids = np.array(process_txt(pr_file), dtype=np.int64)
  File "/home/luca_luis/adl4cv/opennerf/scripts/train_eval_replica_semantics.py", line 12, in process_txt
    with open(filename) as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/luca_luis/adl4cv/opennerf/outputs/replica_office0/opennerf/test_eval/semantics_office0.txt'
```

**Comment by francisengelmann** [comment]
in your output this line seems to show the problem:
"`/home/luca_luis/anaconda3/envs/adl4cv/bin/python: can't open file '/home/luca_luis/adl4cv/opennerf/opennerf/datasets/replica_semantics.py': [Errno 2] No such file or directory`"

The path was most likely wrong, I fixed it in `train_eval_replica_semantics.py`. Can you pull and try again?

**Comment by lusxvr** [comment]
Initially I had the preprocessed data saved in a directory outside the repo and didnt create a virtual link to it but manually changed the data path in the `train_scene` command. This still lead to the same error since I guess the virtual link to the data dir is used somewhere else in the pipeline.
After changing this the rendering of the trajectory video ran through but I still get an error in the evaluation script, concerning some invalid values in the calculations.

```
╭────────────────────────────────────────────── 🎉 Training Finished 🎉 ───────────────────────────────────────────────╮
│                        ╷                                                                                             │
│   Config File          │ /home/luca_luis/adl4cv/opennerf/outputs/replica_office0/opennerf/w_dino_0/config.yml        │
│   Checkpoint Directory │ /home/luca_luis/adl4cv/opennerf/outputs/replica_office0/opennerf/w_dino_0/nerfstudio_mod…   │
│                        ╵                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.0331              
VanillaPipeline.get_train_loss_dict: 0.0098              
Trainer.eval_iteration: 0.0000              
wandb: \ 0.033 MB of 0.033 MB uploaded
wandb: Run history:
wandb:                                     ETA (time) ███▇▇▇▇▇▆▆▆▆▆▅▅▅▅▅▅▄▄▄▄▄▄▃▃▃▃▃▃▂▂▂▂▂▂▁▁▁
wandb:                                GPU Memory (MB) ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                              Train Iter (time) █▅▆▅▄▅▃▄▂▃▃▂▂▃▃▄▂▄▂▃▂▁▃▃▃▃▂▃▃▂▃▃▃▃▂▃▃▂▃▂
wandb:                                     Train Loss ▃▂▇▄█▂▅▃▆▇▄▆▇▄▅▅▅▆▄▄▃▁▆▁▅▄▆▅█▄▄▇▂▄▂▅█▅▄▆
wandb:         Train Loss Dict/camera_opt_regularizer ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                      Train Loss Dict/dino_loss ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                Train Loss Dict/distortion_loss █▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                Train Loss Dict/interlevel_loss ▄▁▁▃▃▄▃▄▅▃▅▆▅▅▇▆▆▅▆▅▆▇█▇▆█▆█▇▇▆▅▇▆▇▆▇▆▆▇
wandb:                   Train Loss Dict/openseg_loss ▃▂▇▄█▂▅▃▆▇▄▆▇▄▅▅▅▆▄▄▃▁▆▁▅▄▆▅█▄▄▇▂▄▂▅█▅▄▆
wandb:                       Train Loss Dict/rgb_loss █▃▂▃▂▂▂▂▁▂▁▂▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:     Train Metrics Dict/camera_opt_rotation_max ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:    Train Metrics Dict/camera_opt_rotation_mean ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:  Train Metrics Dict/camera_opt_translation_max ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: Train Metrics Dict/camera_opt_translation_mean ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                  Train Metrics Dict/distortion █▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                        Train Metrics Dict/psnr ▁▃▄▄▅▅▄▆▆▆▆▆▆▇▇▆▇▇▆▇▆▆▇██▇█▇▇██▇███▇▇██▇
wandb:                               Train Rays / Sec ▁▃▂▅▅▄▅▄▆▅▆▆▆▅▅▅▆▅▆▅▆█▅▅▅▅▆▅▅▆▅▅▅▅▆▅▅▆▅▆
wandb:                             Train Total (time) ▁
wandb:                       learning_rate/camera_opt ██▇▇▆▆▆▅▅▅▅▄▄▄▄▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁
wandb:                           learning_rate/fields ██▇▇▆▆▆▅▅▅▅▄▄▄▄▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁
wandb:                         learning_rate/opennerf █▆▄▃▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:                                     ETA (time) 0.03323
wandb:                                GPU Memory (MB) 3280.90332
wandb:                              Train Iter (time) 0.03323
wandb:                                     Train Loss 9.63744
wandb:         Train Loss Dict/camera_opt_regularizer 0.0
wandb:                      Train Loss Dict/dino_loss 0.0
wandb:                Train Loss Dict/distortion_loss 0.0
wandb:                Train Loss Dict/interlevel_loss 0.00047
wandb:                   Train Loss Dict/openseg_loss 9.63691
wandb:                       Train Loss Dict/rgb_loss 5e-05
wandb:     Train Metrics Dict/camera_opt_rotation_max 0.0
wandb:    Train Metrics Dict/camera_opt_rotation_mean 0.0
wandb:  Train Metrics Dict/camera_opt_translation_max 0.0
wandb: Train Metrics Dict/camera_opt_translation_mean 0.0
wandb:                  Train Metrics Dict/distortion 0.00077
wandb:                        Train Metrics Dict/psnr 42.61663
wandb:                               Train Rays / Sec 61741.14383
wandb:                             Train Total (time) 1030.84942
wandb:                       learning_rate/camera_opt 0.0001
wandb:                           learning_rate/fields 0.001
wandb:                         learning_rate/opennerf 0.001
wandb: 
wandb: 🚀 View run replica_office0 at: https://wandb.ai/lusxvr/nerfstudio-project/runs/ftst5teh
wandb: ⭐️ View project at: https://wandb.ai/lusxvr/nerfstudio-project
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./outputs/replica_office0/opennerf/w_dino_0/wandb/run-20240530_140249-ftst5teh/logs
2024-05-30 14:20:14.908674: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-30 14:20:14.909004: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-30 14:20:14.913197: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-30 14:20:14.937272: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-30 14:20:15.499339: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/luca_luis/anaconda3/envs/adl4cv/lib/python3.10/site-packages/tinycudann/modules.py:52: UserWarning: tinycudann was built for lower compute capability (75) than the system's (86). Performance may be suboptimal.
  warnings.warn(f"tinycudann was built for lower compute capability ({cc}) than the system's ({system_compute_capability}). Performance may be suboptimal.")
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from 
/home/luca_luis/adl4cv/opennerf/outputs/replica_office0/opennerf/w_dino_0/nerfstudio_models/step-000029999.ckpt
/home/luca_luis/anaconda3/envs/adl4cv/lib/python3.10/site-packages/nerfstudio/cameras/camera_utils.py:278: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(traj, dtype=torch.float32), torch.tensor(k_interp, dtype=torch.float32)
Creating trajectory video
🎥 Rendering 🎥 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197/197(100.0%) 0.59 fps 0:00:00 0:05:37
100%|███████████████████████████████████████| 891M/891M [04:52<00:00, 3.20MiB/s]

************************************************************************
1) Start local server:
    cd /home/luca_luis/adl4cv/opennerf/outputs/replica_office0/opennerf/w_dino_0/vis; python -m http.server 6008
2) Open in browser:
    http://localhost:6008
************************************************************************
╭──────────────────────────────── 🎉 Render Complete 🎉 ────────────────────────────────╮
│         ╷                                                                             │
│   Video │ /home/luca_luis/adl4cv/opennerf/outputs/replica_office0/opennerf/w_dino_0   │
│         ╵                                                                             │
╰───────────────────────────────────────────────────────────────────────────────────────╯
evaluating 1 scans...
scans processed: 1/home/luca_luis/adl4cv/opennerf/scripts/train_eval_replica_semantics.py:116: RuntimeWarning: invalid value encountered in divide
  acc = tp / float(tp + fn)
classes          IoU     Acc
----------------------------
wall          : 27.76%   44.63%
ceiling       : 31.26%   31.79%
floor         : 9.87%   86.11%
chair         : 76.46%   88.55%
blinds        : 0.00%    0.00%
sofa          : 83.86%   90.55%
table         : 44.05%   62.58%
rug           : 28.84%   28.84%
Traceback (most recent call last):
  File "/home/luca_luis/adl4cv/opennerf/scripts/train_eval_replica_semantics.py", line 128, in <module>
    main()
  File "/home/luca_luis/adl4cv/opennerf/scripts/train_eval_replica_semantics.py", line 125, in main
    eval_semantics(experiment_name)
  File "/home/luca_luis/adl4cv/opennerf/scripts/train_eval_replica_semantics.py", line 79, in eval_semantics
    print('{0:<14s}: {1:>5.2%}   {2:>6.2%}'.format(label_name, class_ious[label_name][0], class_ious[label_name][1]))
TypeError: 'float' object is not subscriptable
```

**Comment by francisengelmann** [comment]
It's likely a nan since some semantic classes have no scores (needs to be safeguarded) - after running it over all the replica scenes it should work.
